services:
  db:
    image: mariadb:lts
    container_name: mariadb-lts
    command: --transaction-isolation=READ-COMMITTED
    restart: always
    volumes:
      - /mnt/ssd/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=your_secure_root_password
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud

  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  app:
    image: nextcloud:apache
    container_name: nextcloud
    restart: always
    volumes:
      - /mnt/ssd/nextcloud/html:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:apache
    container_name: nextcloud-cron
    restart: always
    volumes:
      - /mnt/ssd/nextcloud/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - default

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    depends_on:
      - app
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /mnt/ssd/nextcloud/Caddyfile:/etc/caddy/Caddyfile
      - /mnt/ssd/nextcloud/caddy_data:/data
      - /mnt/ssd/nextcloud/caddy_config:/config
    networks:
      - proxy-tier

volumes:
  db:
  nextcloud:
  caddy_data:
  caddy_config:

networks:
  proxy-tier:
