version: "3"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --interval
      - "86400" # 24 hours in seconds
      - --cleanup
      - --label-enable
      - --debug
