# Create ~/.secrets.zsh and put your exports there, e.g.:
#   export OPENAI_API_KEY=...
#   export NVIDIA_API_KEY=...
#   export TAVILY_API_KEY=...
#   export KAGGLE_USERNAME=...
#   export KAGGLE_KEY=...
#   export ZOTERO_API_KEY=...
#   export ZOTERO_USER_ID=...
