services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - /mnt/ssd/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /mnt/ssd/caddy/site:/srv

volumes:
  caddy_data:
  caddy_config:
