name: Validate Docker Compose Stacks

on:
  push:
    paths:
      - "docker-compose/**/docker-compose.yml"
  pull_request:
    paths:
      - "docker-compose/**/docker-compose.yml"

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: Jellyfin Stack (GPU)
            path: docker-compose/media-server/jellyfin-arr-stack-nvidia-gpu
            gpu: true
          - name: Nextcloud Stack
            path: docker-compose/nextcloud-reverse-proxy-tailscale
            gpu: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate docker-compose.yml for ${{ matrix.name }}
        working-directory: ${{ matrix.path }}
        run: docker compose config

      - name: Run Docker Compose (non-GPU only)
        if: matrix.gpu == false
        working-directory: ${{ matrix.path }}
        run: docker compose up -d

      - name: Tear Down Docker Compose (non-GPU only)
        if: matrix.gpu == false && always()
        working-directory: ${{ matrix.path }}
        run: docker compose down
