name: Validate Docker Compose Stacks

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: cloudflare-caddy/immich
            path: docker-compose/cloudflare-caddy-reverse-proxy-tailscale/immich
            gpu: false
            host_mounts: true
            upload_location: /tmp/immich/uploads
            db_data_location: /tmp/immich/postgres
            db_password: immich
            db_username: immich
            db_database_name: immich
          - name: cloudflare-caddy/pihole
            path: docker-compose/cloudflare-caddy-reverse-proxy-tailscale/pihole
            gpu: false
            host_mounts: true
            upload_location: /tmp/uploads-unused
            db_data_location: /tmp/db-unused
            db_password: placeholder
            db_username: placeholder
            db_database_name: placeholder
          - name: old-free/media-server/jellyfin-arr-stack-nvidia-gpu
            path: docker-compose/old-free-tailscale-reverse-proxy/media-server/jellyfin-arr-stack-nvidia-gpu
            gpu: true
            host_mounts: true
            upload_location: /tmp/uploads-unused
            db_data_location: /tmp/db-unused
            db_password: placeholder
            db_username: placeholder
            db_database_name: placeholder
          - name: old-free/nextcloud-reverse-proxy-tailscale
            path: docker-compose/old-free-tailscale-reverse-proxy/nextcloud-reverse-proxy-tailscale
            gpu: false
            host_mounts: true
            upload_location: /tmp/uploads-unused
            db_data_location: /tmp/db-unused
            db_password: placeholder
            db_username: placeholder
            db_database_name: placeholder

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate docker-compose.yml for ${{ matrix.name }}
        working-directory: ${{ matrix.path }}
        env:
          UPLOAD_LOCATION: ${{ matrix.upload_location }}
          DB_DATA_LOCATION: ${{ matrix.db_data_location }}
          DB_PASSWORD: ${{ matrix.db_password }}
          DB_USERNAME: ${{ matrix.db_username }}
          DB_DATABASE_NAME: ${{ matrix.db_database_name }}
        run: docker compose config

      - name: Run Docker Compose (non-GPU, no host mounts)
        if: matrix.gpu == false && matrix.host_mounts == false
        working-directory: ${{ matrix.path }}
        env:
          UPLOAD_LOCATION: ${{ matrix.upload_location }}
          DB_DATA_LOCATION: ${{ matrix.db_data_location }}
          DB_PASSWORD: ${{ matrix.db_password }}
          DB_USERNAME: ${{ matrix.db_username }}
          DB_DATABASE_NAME: ${{ matrix.db_database_name }}
        run: docker compose up -d

      - name: Tear Down Docker Compose (non-GPU, no host mounts)
        if: matrix.gpu == false && matrix.host_mounts == false && always()
        working-directory: ${{ matrix.path }}
        env:
          UPLOAD_LOCATION: ${{ matrix.upload_location }}
          DB_DATA_LOCATION: ${{ matrix.db_data_location }}
          DB_PASSWORD: ${{ matrix.db_password }}
          DB_USERNAME: ${{ matrix.db_username }}
          DB_DATABASE_NAME: ${{ matrix.db_database_name }}
        run: docker compose down
