name: Validate AeroSpace Config

on:
  push:
    branches:
      - "**"
    paths:
      - "aerospace/aerospace.toml"
  pull_request:
    branches:
      - "**"
    paths:
      - "aerospace/aerospace.toml"
  workflow_dispatch:

jobs:
  validate-config:
    name: Validate aerospace.toml
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install toml-lint
        run: |
          curl -sSL https://github.com/pelletier/go-toml/releases/latest/download/toml-lint_linux_amd64.tar.gz | tar xz
          sudo mv toml-lint /usr/local/bin/

      - name: Run toml-lint on aerospace config
        run: toml-lint aerospace/aerospace.toml
